### ISSUE TITLE
Updates to buffer-store plugin.

### ISSUE THREAD

**Issue by AxerTheAxe** [yutkat/my-neovim-pluginlist#1288]
Hello, thanks for including my plugin here. Due to some issues I had to delete and reupload the plugin in again. I also changed the name of the repository and some parts of the plugin configuration. If you are still interested in including the plugin then it can be found again [here](https://github.com/AxerTheAxe/buffer-store.nvim).

**Comment by yutkat** [comment]
Thank you for info. I updated it.
https://github.com/yutkat/my-neovim-pluginlist/commit/38fbb13df7e5d1a27a680ba3f10b7d30431b78d8
