### ISSUE TITLE
Fix the link for the `Colorker.nvim` plugin

### ISSUE THREAD

**Issue by farias-hecdin** [yutkat/my-neovim-pluginlist#1435]
Hello, How are you? 👋

First, I want to congratulate you on this project and thank you for including my `Colorker.nvim` plugin in it. I feel honored that you have considered my work useful for your project. 😍

Also, I wanted to let you know that I have been working on improving my plugin and have decided to rename it from `Colorker.nvim` to `CSSVarHighlight`, a name that I believe is more descriptive and easier to understand. 👍

You can find the plugin in its new repository on GitHub: https://github.com/farias-hecdin/CSSVarHighlight 👀

So I wanted to ask you: if you would be so kind as to update the link in your project to point to the new name of the plugin. 🙏

**Comment by yutkat** [comment]
Thank you. I updated it.
https://github.com/yutkat/my-neovim-pluginlist/commit/6824a243445ea75a7b8580a0b15593e8b5964536
