### ISSUE TITLE
Misplaced snippet plugin?

### ISSUE THREAD

**Issue by telemachus** [yutkat/my-neovim-pluginlist#1503]
Great list: thanks for sharing. I think that LuaSnip-ulid.nvim belongs under LuaSnip rather than under nvim-snippy.

**Comment by yutkat** [comment]
Indeed. Thank you. Fixed.

https://github.com/yutkat/my-neovim-pluginlist/commit/e776fd7278ea753090fd87de413eea3bec467e64
