### ISSUE TITLE
I'm about to delete two of my nvim plugins

### ISSUE THREAD

**Issue by haolian9** [yutkat/my-neovim-pluginlist#505]
hi, I noticed that you have listed them in this repo, so I feel I'd better to tell you about it.

* https://github.com/haolian9/lingboweibu.nvim
* https://github.com/haolian9/folding.nvim

In their later development, the two plugins were so bound to my nvim core configuration that i can not split them out. (there are several many depends I need to expose, and i think it's not worth it for the maintain burden)

**Comment by haolian9** [comment]
oh wow, this issue makes me wonder if there is a dead-link-detect github action, if so, that would be super useful.

**Comment by yutkat** [comment]
If you archive (or delete) those repositories, I will delete them.

Now, I'm using curl (https://github.com/yutkat/my-neovim-pluginlist/actions/runs/3617442878/jobs/6096288646) to check if the repo is Archived.

**Comment by haolian9** [comment]
oh great, nice to know that.
